In [1]:
import pandas as pd

In [11]:
df=pd.read_csv("Heart_dataset.csv")

In [3]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [4]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='str')

In [12]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [8]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [14]:
df.fillna(df.mean(numeric_only=True),inplace=True)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.000000,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.000000,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.000000,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.000000,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.000000,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.000000,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.000000,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.000000,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.000000,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,0.672241,normal,No

In [16]:
df.fillna(df.mode().iloc[0],inplace=True)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.000000,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.000000,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.000000,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.000000,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.000000,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,0.000000,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.000000,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.000000,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.000000,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,0.672241,normal,No

In [17]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [48]:
ds1=df[(df['ChestPain']=='typical') & (df['Thal']!='fixed')][['Age','Sex']]

In [49]:
ds1

     Age  Sex
20    64    1
21    58    0
27    66    0
30    69    0
41    40    1
59    51    1
101   34    1
124   65    1
141   59    1
150   52    1
182   42    1
183   59    1
196   69    1
199   59    1
211   38    1
215   56    1
243   61    1
262   60    0
274   59    1
275   64    1
298   45    1

In [52]:
ds1.shape

(21, 2)

In [57]:
ds2=df[(df['Age']<50) & (df['Sex']==1)][['Slope','Ca']]

In [58]:
ds2.shape

(63, 2)

In [67]:
frame=[ds1,ds2]
ds3=pd.concat(frame)

In [68]:
ds3

      Age  Sex  Slope        Ca
20   64.0  1.0    NaN       NaN
21   58.0  0.0    NaN       NaN
27   66.0  0.0    NaN       NaN
30   69.0  0.0    NaN       NaN
41   40.0  1.0    NaN       NaN
..    ...  ...    ...       ...
283   NaN  NaN    1.0  0.000000
292   NaN  NaN    3.0  0.000000
295   NaN  NaN    1.0  0.000000
298   NaN  NaN    2.0  0.000000
302   NaN  NaN    1.0  0.672241

[84 rows x 4 columns]

In [69]:
ds4=ds2.T

In [70]:
ds4

,3,13,16,19,28,29,34,35,36,41,...,265,268,269,272,281,283,292,295,298,302
Slope,3.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,...,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,2.0,1.000000
Ca,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.672241

In [71]:
df.sort_values('MaxHR')

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
245,67,1,asymptomatic,120,237,0,0,71,0,1.0,2,0.0,normal,Yes
175,57,1,asymptomatic,152,274,0,0,88,1,1.2,2,1.0,reversable,Yes
296,59,1,asymptomatic,164,176,1,2,90,0,1.0,2,2.0,fixed,Yes
223,53,1,asymptomatic,123,282,0,0,95,1,2.0,2,2.0,reversable,Yes
154,64,1,asymptomatic,120,246,0,2,96,1,2.2,3,1.0,normal,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,52,1,typical,118,186,0,2,190,0,0.0,2,0.0,fixed,No
225,34,0,nontypical,118,210,0,0,192,0,0.7,1,0.0,normal,No
186,42,1,nonanginal,120,240,1,0,194,0,0.8,3,0.0,reversable,No
188,54,1,nontypical,192,283,0,2,195,0,0.0,1,1.0,reversable,Yes
132,29,1,nontypical,130,204,0,2,202,0,0.0,1,0.0,normal,No